--- 
development: 
  adapter: postgresql
  database: myapp_development
  encoding: unicode
  password: ~
  pool: 5
  username: myapp
production: 
  adapter: postgresql
  database: myapp_production
  encoding: unicode
  pool: 5
test: 
  adapter: postgresql
  database: myapp_test
  encoding: unicode
  password: ~
  pool: 5
  username: myapp
username: "myapp password:"
